data_paths:
  raw_data_path : ./../artifacts/data/raw_data/
  clean_data_path : ./../artifacts/data/cleaned_data/
  processed_data_path : ./../artifacts/data/processed_data/
  raw_data_file : homeprices.csv
  model_path: './../artifacts/model/raw_model/'
  best_model_path : './../artifacts/model/best_model/'
preprocess:
  test_size : 0.5
  Target : price
model:
  fit_intercept : True
mlflow:
  experiment_name : test
  run_name : first_model
flask_app:
  best_model_path : './app/artifacts/model/best_model/'


  
