data_paths:
  raw_data_path : ./../artifacts/data/raw_data/
  clean_data_path : ./../artifacts/data/cleaned_data/
  processed_data_path : ./../artifacts/data/processed_data/
  raw_data_file : homeprices.csv
  model_path: './../artifacts/model/raw_model/'
preprocess:
  test_size : 0.3
  Target : price
model:
  fit_intercept : True
mlflow:
  run_name : first_model

  
